before_install:
    - gem update --system
    - gem install bundler
    - bundle install
    - bundle exec pod install --repo-update
    - gem install linterbot
    - brew install swiftlint
cache:
  - bundler
  - cocoapods
language: objective-c
osx_image: xcode10
xcode_project: Pikalong.xcworkspace
xcode_scheme: Pikalong
xcode_destination: platform=iOS Simulator, OS=10.0, name=iPhone 8
script:
    - ./scripts/lint
    - bundle exec fastlane test
install:
    - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
